apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: monitoring
spec:
  selector:
    app-1: grafana
    app-2: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
    
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300
  type: NodePort